version: '3.8'

services:
  backend:
    image: rorrenss/backendpractica:1
    container_name: backendJV
    ports:
      - "8082:8082"
    networks:
      - practica2
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./Comunidades_Agrupadas.json:/app/Comunidades_Agrupadas.json

  frontend:
    image: rorrenss/frontendpractica:1
    container_name: frontendJv
    ports:
      - "8207:8081"
    networks:
      - practica2
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend-service:8082

networks:
  practica2:
    driver: bridge
